# Generated by Django 5.1.15 on 2026-06-19 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (€)')),
                ('tipo_cobro', models.CharField(choices=[('por_dia', 'Por día'), ('unico', 'Pago único')], default='por_dia', max_length=10, verbose_name='Tipo de cobro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Volkswagen California 2022', max_length=120, verbose_name='Nombre comercial')),
                ('matricula', models.CharField(max_length=15, unique=True, verbose_name='Matrícula')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('categoria', models.CharField(choices=[('turismo', 'Turismo'), ('furgoneta', 'Furgoneta'), ('camper', 'Camper'), ('industrial', 'Industrial'), ('moto', 'Moto')], default='furgoneta', max_length=20, verbose_name='Categoría')),
                ('plazas', models.PositiveSmallIntegerField(default=5, verbose_name='Plazas')),
                ('puertas', models.PositiveSmallIntegerField(default=4, verbose_name='Puertas')),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], default='diesel', max_length=20, verbose_name='Combustible')),
                ('cambio', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20, verbose_name='Cambio')),
                ('capacidad_carga', models.CharField(blank=True, help_text="Texto libre, ej: '3,2 m³ / 1000 kg'", max_length=60, verbose_name='Capacidad de carga')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fianza', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fianza/depósito (€)')),
                ('km_actuales', models.PositiveIntegerField(default=0, verbose_name='Kilómetros actuales')),
                ('activo', models.BooleanField(default=True, help_text='Si se desmarca, no aparece en la web ni admite reservas.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extras', models.ManyToManyField(blank=True, related_name='vehiculos', to='autorent.extra', verbose_name='Extras disponibles')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TemporadaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Temporada alta verano', max_length=80, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Desde')),
                ('fecha_fin', models.DateField(verbose_name='Hasta')),
                ('tipo_ajuste', models.CharField(choices=[('multiplicador', 'Multiplicador (ej: 1.30 = +30%)'), ('precio_fijo', 'Precio fijo por día (€)')], default='multiplicador', max_length=20, verbose_name='Tipo de ajuste')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si es multiplicador: 1.30. Si es precio fijo: el €/día.', max_digits=8, verbose_name='Valor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Temporada de precio',
                'verbose_name_plural': 'Temporadas de precio',
                'ordering': ['vehiculo', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RangoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_min', models.PositiveSmallIntegerField(verbose_name='Días mínimo')),
                ('dias_max', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = sin límite superior.', null=True, verbose_name='Días máximo')),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por día (€)')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos_precio', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Rango de precio',
                'verbose_name_plural': 'Rangos de precio',
                'ordering': ['vehiculo', 'dias_min'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('itv', 'ITV'), ('revision', 'Revisión'), ('neumaticos', 'Neumáticos'), ('seguro', 'Seguro'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='revision', max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_proximo', models.DateField(blank=True, help_text='Para alertas (ej: próxima ITV).', null=True, verbose_name='Próximo vencimiento')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km en el momento')),
                ('coste', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coste (€)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/', verbose_name='Imagen')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Foto de vehículo',
                'verbose_name_plural': 'Fotos de vehículos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Desde')),
                ('fecha_fin', models.DateField(verbose_name='Hasta')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Bloqueo de fechas',
                'verbose_name_plural': 'Bloqueos de fechas',
                'ordering': ['vehiculo', 'fecha_inicio'],
            },
        ),
    ]