# Generated by Django 5.1.15 on 2026-06-22 15:33

import autorent.models.reserva
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=160, verbose_name='Apellidos')),
                ('nif', models.CharField(max_length=20, verbose_name='NIF/DNI/Pasaporte')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('poblacion', models.CharField(blank=True, max_length=100, verbose_name='Población')),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('pais', models.CharField(default='España', max_length=60, verbose_name='País')),
                ('carnet_numero', models.CharField(blank=True, max_length=40, verbose_name='Nº carnet de conducir')),
                ('carnet_caducidad', models.DateField(blank=True, null=True, verbose_name='Caducidad del carnet')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Localizador')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de recogida')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de devolución')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('documentacion', 'Pendiente de documentación'), ('confirmada', 'Confirmada'), ('activa', 'Activa (en curso)'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta (online)'), ('efectivo', 'Efectivo / en oficina')], default='transferencia', max_length=20, verbose_name='Método de pago')),
                ('num_dias', models.PositiveSmallIntegerField(default=0, verbose_name='Nº de días')),
                ('precio_dia_base', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio/día base')),
                ('subtotal_vehiculo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal vehículo')),
                ('subtotal_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal extras')),
                ('fianza', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fianza')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (sin fianza)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='autorent.cliente', verbose_name='Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta (online)'), ('efectivo', 'Efectivo / en oficina')], max_length=20, verbose_name='Método')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('referencia', models.CharField(blank=True, help_text='ID de transacción de pasarela o concepto de transferencia.', max_length=120, verbose_name='Referencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de factura')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total facturado')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='PDF')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dni_anverso', 'DNI (anverso)'), ('dni_reverso', 'DNI (reverso)'), ('carnet', 'Carnet de conducir'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('archivo', models.FileField(upload_to=autorent.models.reserva.documento_upload_path, verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('notas_revision', models.CharField(blank=True, max_length=255, verbose_name='Notas de revisión')),
                ('subido_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Documento de reserva',
                'verbose_name_plural': 'Documentos de reserva',
                'ordering': ['reserva', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cancelación')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('importe_reembolsado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe reembolsado')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelacion', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Cancelación',
                'verbose_name_plural': 'Cancelaciones',
            },
        ),
        migrations.CreateModel(
            name='ReservaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_congelado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio congelado')),
                ('tipo_cobro_congelado', models.CharField(max_length=10, verbose_name='Tipo de cobro')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='autorent.extra', verbose_name='Extra')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_contratados', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Extra contratado',
                'verbose_name_plural': 'Extras contratados',
            },
        ),
    ]