# Generated by Django 5.1.15 on 2026-06-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0002_cliente_reserva_pago_factura_documentoreserva_and_more'),
        ('core', '0002_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='sede_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_entrega', to='core.sede', verbose_name='Sede de entrega'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sede_recogida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_recogida', to='core.sede', verbose_name='Sede de recogida'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='core.sede', verbose_name='Sede base'),
        ),
    ]