# Generated by Django 5.1.15 on 2026-06-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0004_vehiculo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=160, verbose_name='Apellidos')),
                ('nif', models.CharField(max_length=20, verbose_name='NIF/DNI/Pasaporte')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('carnet_numero', models.CharField(max_length=40, verbose_name='Nº carnet de conducir')),
                ('carnet_caducidad', models.DateField(verbose_name='Caducidad del carnet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores_adicionales', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Conductor adicional',
                'verbose_name_plural': 'Conductores adicionales',
            },
        ),
    ]