# Generated by Django 5.1.15 on 2026-06-24 09:27

import autorent.models.reserva
import autorent.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0005_conductoradicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoreserva',
            name='archivo',
            field=models.FileField(storage=autorent.storage.DocumentosStorage(), upload_to=autorent.models.reserva.documento_upload_path, verbose_name='Archivo'),
        ),
    ]