# Generated by Django 5.1.15 on 2026-06-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0006_alter_documentoreserva_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoreserva',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Si el documento es de un conductor adicional. Vacío = del titular.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='autorent.conductoradicional', verbose_name='Conductor adicional'),
        ),
        migrations.CreateModel(
            name='TokenSubida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('expira_at', models.DateTimeField(verbose_name='Expira')),
                ('usado_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_subida', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Token de subida',
                'verbose_name_plural': 'Tokens de subida',
                'ordering': ['-creado_at'],
            },
        ),
    ]