# Generated by Django 5.1.15 on 2026-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0007_documentoreserva_conductor_tokensubida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='doc_estado_notificado',
            field=models.CharField(blank=True, default='', editable=False, max_length=12, verbose_name='Estado doc. notificado'),
        ),
    ]