# Generated by Django 5.1.15 on 2026-06-24 15:57

import autorent.models.reserva
import autorent.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0008_reserva_doc_estado_notificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, storage=autorent.storage.DocumentosStorage(), upload_to=autorent.models.reserva.contrato_upload_path, verbose_name='Contrato PDF')),
                ('hash_sha256', models.CharField(blank=True, editable=False, help_text='Huella del PDF generado, para integridad/auditoría.', max_length=64, verbose_name='Hash SHA-256')),
                ('generado_at', models.DateTimeField(blank=True, null=True, verbose_name='Generado')),
                ('enviado_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado al cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='autorent.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]