# Generated by Django 5.1.15 on 2026-06-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0009_contratoreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(db_index=True, help_text='Identificador único del dispositivo (15 dígitos).', max_length=20, unique=True, verbose_name='IMEI')),
                ('modelo', models.CharField(choices=[('fmc130', 'Teltonika FMC130'), ('fmc003', 'Teltonika FMC003'), ('otro', 'Otro')], default='fmc130', max_length=10, verbose_name='Modelo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultima_comunicacion', models.DateTimeField(blank=True, null=True, verbose_name='Última comunicación')),
                ('sim_iccid', models.CharField(blank=True, max_length=25, verbose_name='ICCID de la SIM')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='autorent.vehiculo', verbose_name='Vehículo asignado')),
            ],
            options={
                'verbose_name': 'Dispositivo GPS',
                'verbose_name_plural': 'Dispositivos GPS',
                'ordering': ['imei'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Fecha/hora')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('altitud', models.FloatField(blank=True, null=True, verbose_name='Altitud (m)')),
                ('rumbo', models.FloatField(blank=True, null=True, verbose_name='Rumbo (°)')),
                ('satelites', models.IntegerField(blank=True, null=True, verbose_name='Satélites')),
                ('velocidad', models.FloatField(default=0, verbose_name='Velocidad (km/h)')),
                ('ignicion', models.BooleanField(default=False, verbose_name='Encendido (ignición)')),
                ('movimiento', models.BooleanField(default=False, verbose_name='En movimiento')),
                ('odometro', models.BigIntegerField(blank=True, help_text='Kilometraje real leído del vehículo.', null=True, verbose_name='Odómetro (km)')),
                ('nivel_combustible', models.FloatField(blank=True, null=True, verbose_name='Nivel de combustible (%)')),
                ('voltaje_bateria', models.FloatField(blank=True, null=True, verbose_name='Voltaje batería (V)')),
                ('aceleracion_x', models.FloatField(blank=True, null=True, verbose_name='Acel. X')),
                ('aceleracion_y', models.FloatField(blank=True, null=True, verbose_name='Acel. Y')),
                ('aceleracion_z', models.FloatField(blank=True, null=True, verbose_name='Acel. Z')),
                ('evento_id', models.IntegerField(blank=True, null=True, verbose_name='Evento (IO id)')),
                ('recibido_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='autorent.dispositivo', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['dispositivo', '-timestamp'], name='autorent_po_disposi_ea1de1_idx')],
            },
        ),
    ]