# Generated by Django 5.1.15 on 2026-06-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0010_dispositivo_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('velocidad', 'Exceso de velocidad'), ('conduccion', 'Conducción brusca')], max_length=20, verbose_name='Tipo')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída/atendida')),
                ('clave_dedupe', models.CharField(blank=True, db_index=True, editable=False, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReglaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aceite', 'Cambio de aceite'), ('neumaticos', 'Neumáticos'), ('itv', 'ITV'), ('revision', 'Revisión general'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('cada_km', models.PositiveIntegerField(blank=True, help_text='Intervalo en km (ej: aceite cada 15000). Vacío si es por fecha.', null=True, verbose_name='Cada (km)')),
                ('km_proximo', models.PositiveIntegerField(blank=True, help_text='Odómetro al que saltará el aviso.', null=True, verbose_name='Próximo aviso (km)')),
                ('fecha_proxima', models.DateField(blank=True, null=True, verbose_name='Próxima fecha')),
                ('dias_aviso', models.PositiveIntegerField(default=15, verbose_name='Avisar con (días) de antelación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_mantenimiento', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Regla de mantenimiento',
                'verbose_name_plural': 'Reglas de mantenimiento',
                'ordering': ['vehiculo', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='EventoConduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frenazo', 'Frenazo brusco'), ('aceleron', 'Aceleración brusca'), ('curva', 'Curva brusca'), ('velocidad', 'Exceso de velocidad')], max_length=12, verbose_name='Tipo')),
                ('severidad', models.FloatField(default=1.0, help_text='Magnitud del evento (g del acelerómetro o km/h de exceso).', verbose_name='Severidad')),
                ('velocidad', models.FloatField(blank=True, null=True, verbose_name='Velocidad (km/h)')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Momento')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_conduccion', to='autorent.reserva', verbose_name='Reserva activa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_conduccion', to='autorent.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Evento de conducción',
                'verbose_name_plural': 'Eventos de conducción',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehiculo', '-timestamp'], name='autorent_ev_vehicul_0b7e44_idx')],
            },
        ),
    ]