# Generated by Django 5.1.15 on 2026-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0011_alerta_reglamantenimiento_eventoconduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='limite_velocidad',
            field=models.PositiveIntegerField(blank=True, help_text='Para alertas de exceso. Si se deja vacío, se usa el límite por defecto de su categoría.', null=True, verbose_name='Límite de velocidad (km/h)'),
        ),
    ]