# Generated by Django 5.1.15 on 2026-06-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0012_vehiculo_limite_velocidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador estable para el filtro del catálogo (ej: turismo).', max_length=40, unique=True, verbose_name='Código (slug)')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('limite_velocidad', models.PositiveIntegerField(default=120, help_text='Se aplica a los vehículos de esta categoría que no tengan un límite propio.', verbose_name='Límite de velocidad por defecto (km/h)')),
                ('edad_min_conductor', models.PositiveIntegerField(default=23, verbose_name='Edad mínima del conductor (años)')),
                ('antiguedad_carnet_min', models.PositiveIntegerField(default=2, verbose_name='Antigüedad mínima de carnet (años)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar las categorías en listados y filtros.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de vehículo',
                'verbose_name_plural': 'Categorías de vehículo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='autorent.categoriavehiculo', verbose_name='Categoría (gestionable)'),
        ),
    ]