# Generated by Django 5.1.15 on 2026-06-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0014_poblar_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='recordatorio_24h_enviado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recordatorio_48h_enviado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]