# Generated by Django 5.1.15 on 2026-06-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorent', '0017_recordatorios_horario_9h'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrega'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_recogida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de recogida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='suplemento_fuera_horario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Suplemento fuera de horario (€)'),
        ),
    ]