# Generated by Django 5.1.15 on 2026-06-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.ejemplo.com', max_length=100, verbose_name='Servidor SMTP')),
                ('email_port', models.IntegerField(default=587, verbose_name='Puerto')),
                ('email_host_user', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('email_host_password', models.CharField(blank=True, max_length=200, verbose_name='Contraseña')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_from_default', models.CharField(default='AutoRent <reservas@autorent.automaworks.es>', max_length=200, verbose_name='Remitente por defecto (FROM)')),
                ('email_dns_workaround', models.CharField(blank=True, help_text='Si el envío falla por DNS, pon aquí tu dominio (ej: automaworks.es).', max_length=100, verbose_name='Fix DNS (opcional)')),
            ],
            options={
                'verbose_name': 'Configuración SMTP',
                'verbose_name_plural': 'Configuración SMTP',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='AutoRent', max_length=200, verbose_name='Nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF/CIF')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('poblacion', models.CharField(blank=True, max_length=100, verbose_name='Población')),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('banco_titular', models.CharField(blank=True, max_length=200, verbose_name='Titular de la cuenta')),
                ('banco_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('banco_bic', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('color_primary', models.CharField(default='#1c3042', help_text='Hex, ej: #1c3042', max_length=7, verbose_name='Color primario')),
                ('color_accent', models.CharField(default='#0891b3', help_text='Hex, ej: #0891b3', max_length=7, verbose_name='Color de acento')),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuración de empresa',
            },
        ),
    ]