# Generated by Django 5.1.15 on 2026-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('poblacion', models.CharField(blank=True, max_length=100, verbose_name='Población')),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('pais', models.CharField(default='España', max_length=60, verbose_name='País')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('horario', models.TextField(blank=True, help_text='Texto libre.', verbose_name='Horario')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]