# Generated by Django 5.1.15 on 2026-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.CharField(default='#f5f7fb', max_length=40, verbose_name='--bg')),
                ('bg_2', models.CharField(default='#ffffff', max_length=40, verbose_name='--bg-2')),
                ('surface', models.CharField(default='rgba(15, 23, 42, 0.028)', max_length=40, verbose_name='--surface')),
                ('surface_2', models.CharField(default='rgba(15, 23, 42, 0.048)', max_length=40, verbose_name='--surface-2')),
                ('surface_3', models.CharField(default='rgba(15, 23, 42, 0.07)', max_length=40, verbose_name='--surface-3')),
                ('border', models.CharField(default='rgba(15, 23, 42, 0.07)', max_length=40, verbose_name='--border')),
                ('border_2', models.CharField(default='rgba(15, 23, 42, 0.12)', max_length=40, verbose_name='--border-2')),
                ('text', models.CharField(default='#0f172a', max_length=40, verbose_name='--text')),
                ('text_2', models.CharField(default='#4b5c78', max_length=40, verbose_name='--text-2')),
                ('accent', models.CharField(default='#0891b2', max_length=40, verbose_name='--accent')),
                ('accent_dim', models.CharField(default='rgba(8, 145, 178, 0.08)', max_length=40, verbose_name='--accent-dim')),
                ('accent_glow', models.CharField(default='rgba(8, 145, 178, 0.05)', max_length=40, verbose_name='--accent-glow')),
                ('shadow', models.CharField(default='0 20px 50px rgba(15, 23, 42, 0.07)', max_length=80, verbose_name='--shadow')),
                ('font_display', models.CharField(choices=[('Cabin', 'Cabin'), ('DM Sans', 'DM Sans'), ('Oxygen', 'Oxygen'), ('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Work Sans', 'Work Sans'), ('Nunito', 'Nunito'), ('Rubik', 'Rubik'), ('Manrope', 'Manrope')], default='Cabin', max_length=40, verbose_name='Fuente de títulos (--font-display)')),
                ('font_body', models.CharField(choices=[('Cabin', 'Cabin'), ('DM Sans', 'DM Sans'), ('Oxygen', 'Oxygen'), ('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Work Sans', 'Work Sans'), ('Nunito', 'Nunito'), ('Rubik', 'Rubik'), ('Manrope', 'Manrope')], default='DM Sans', max_length=40, verbose_name='Fuente de texto (--font-body)')),
            ],
            options={
                'verbose_name': 'Frontend (colores y fuentes)',
                'verbose_name_plural': 'Frontend (colores y fuentes)',
            },
        ),
    ]