# Generated by Django 5.1.15 on 2026-06-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_frontendconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='suplemento_fuera_horario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se aplica automáticamente si la hora elegida cae fuera de las franjas horarias de la sede. 0 = no se permite/cobra.', max_digits=7, verbose_name='Suplemento fuera de horario (€)'),
        ),
        migrations.CreateModel(
            name='FranjaHorariaSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('hora_apertura', models.TimeField(verbose_name='Apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Cierre')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Franja horaria',
                'verbose_name_plural': 'Franjas horarias',
                'ordering': ['sede', 'dia_semana', 'hora_apertura'],
            },
        ),
    ]